-- MateHub general-service schema.
-- All IDs are 63-bit positive BIGINT Snowflakes generated by the application
-- (matehub-common::snowflake). Matches the hub-cluster ID space; no shared
-- generator coordination — different machine_ids via private-IP fallback.

-- ── Accounts (SaaS signup) ───────────────────────
CREATE TABLE accounts (
    id              BIGINT PRIMARY KEY,
    email           TEXT NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,
    email_verified  BOOLEAN NOT NULL DEFAULT FALSE,
    display_name    TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX accounts_email_lower ON accounts (lower(email));

-- ── Hub registry (tenant registry for K8s provisioner) ──
-- hub_secret: 32-byte random, hex-encoded (64 chars). Dual purpose:
--   (a) the hub pod signs its own JWTs with it — so a token from hub A
--       can never be verified by hub B's verifier;
--   (b) the hub pod uses it as Bearer when calling general's
--       /internal/auth/exchange, so general knows which hub is talking.
CREATE TABLE hubs (
    id                BIGINT PRIMARY KEY,
    slug              TEXT NOT NULL UNIQUE,
    name              TEXT NOT NULL,
    owner_account_id  BIGINT NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
    status            TEXT NOT NULL DEFAULT 'provisioning',
    hub_secret        TEXT NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT hubs_slug_format CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$'),
    CONSTRAINT hubs_status_valid CHECK (status IN ('provisioning', 'ready', 'failed', 'deleting'))
);

CREATE INDEX hubs_owner ON hubs (owner_account_id);
-- Reverse lookup for /internal/auth/exchange: given Bearer hub_secret, find
-- the hub it belongs to. Unique to force one-secret-per-hub invariant.
CREATE UNIQUE INDEX hubs_hub_secret ON hubs (hub_secret);

-- ── Hub members (who can "Enter Hub" from dashboard) ───
CREATE TABLE hub_members (
    hub_id      BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    account_id  BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    role        TEXT NOT NULL,
    added_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (hub_id, account_id),
    CONSTRAINT hub_members_role_valid CHECK (role IN ('owner', 'admin', 'member'))
);

CREATE INDEX hub_members_by_account ON hub_members (account_id);

-- ── Mail outbox (transactional email queue) ────────
CREATE TABLE mail_outbox (
    id            BIGINT PRIMARY KEY,
    template      TEXT NOT NULL,
    to_email      TEXT NOT NULL,
    payload       JSONB NOT NULL,
    status        TEXT NOT NULL DEFAULT 'pending',
    attempts      INT NOT NULL DEFAULT 0,
    last_error    TEXT,
    message_id    TEXT,
    scheduled_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at       TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT mail_outbox_status_valid
        CHECK (status IN ('pending', 'sending', 'sent', 'failed'))
);

CREATE INDEX mail_outbox_pending
    ON mail_outbox (scheduled_at)
    WHERE status = 'pending';

-- ── Email verification tokens ─────────────────────
-- token_hash stays text (SHA-256 hex); account_id becomes bigint.
CREATE TABLE email_verification_tokens (
    token_hash   TEXT PRIMARY KEY,
    account_id   BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    expires_at   TIMESTAMPTZ NOT NULL,
    consumed_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX email_verification_tokens_account
    ON email_verification_tokens (account_id)
    WHERE consumed_at IS NULL;

-- ── SSO auth codes ──────────────────────────────────────
-- Single-use, short-lived (30s) handoff codes. general issues one when a
-- logged-in account clicks "Enter hub X" on the dashboard; hub pod redeems
-- it at /internal/auth/exchange for the account info.
CREATE TABLE auth_codes (
    code         TEXT PRIMARY KEY,
    account_id   BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    hub_id       BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    expires_at   TIMESTAMPTZ NOT NULL,
    consumed_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Periodic cleanup of consumed + expired codes happens via app-side
-- background task; index keeps that query cheap.
CREATE INDEX auth_codes_expired
    ON auth_codes (expires_at)
    WHERE consumed_at IS NULL;
