-- MateHub hub-service schema.
-- All IDs are 63-bit positive BIGINT Snowflakes generated by the application
-- (see matehub-common::snowflake). No sequences or uuid-ossp — generators live
-- in Rust so every service in the cluster agrees on the ID space.

-- ── Users ────────────────────────────────────────
-- One identity model for everyone: permanent accounts, SSO accounts, AND
-- temp/guest sessions. The `user_type` discriminator tells them apart;
-- type-specific metadata lives in side-tables (temp_users, refresh_tokens).
-- Putting guests here means messages.sender_id, mentions, reactions, etc.
-- all FK to a single users.id space — history JOINs work the same way for
-- guests as for members, including after the guest's session expires.
--
-- account_id: link to the SaaS-side `general.accounts.id` for users that
-- came through SSO. NULL for on-prem users and temp users. UNIQUE so one
-- general account maps to exactly one hub user (multiple NULLs allowed by
-- Postgres).
--
-- expires_at / deleted_at: lifecycle gates checked on every login / token
-- issue. Hard DELETE FROM users is forbidden — it would cascade-nuke chat
-- history. Instead we soft-delete (set deleted_at, scrub PII) so JOINs keep
-- resolving to "Deleted User" instead of NULL.
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT PRIMARY KEY,
    username      TEXT NOT NULL UNIQUE,
    display_name  TEXT NOT NULL,
    avatar_url    TEXT,
    email         TEXT,
    password_hash TEXT,                                 -- NULL for SSO and temp
    account_id    BIGINT UNIQUE,
    user_type     TEXT NOT NULL DEFAULT 'permanent'
                       CHECK (user_type IN ('permanent', 'temp')),
    expires_at    TIMESTAMPTZ,                          -- only set for temp
    deleted_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email) WHERE email IS NOT NULL;

-- ── Hubs ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS hubs (
    id          BIGINT PRIMARY KEY,
    name        TEXT NOT NULL,
    slug        TEXT NOT NULL UNIQUE,
    plan        TEXT NOT NULL DEFAULT 'free',   -- free, pro, enterprise
    avatar_url  TEXT,
    creator_id  BIGINT REFERENCES users(id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Hub members (many-to-many) ───────────────────
CREATE TABLE IF NOT EXISTS hub_members (
    hub_id        BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role          TEXT NOT NULL DEFAULT 'member',  -- admin, member, guest
    joined_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ,
    PRIMARY KEY (hub_id, user_id)
);

-- ── Channels ─────────────────────────────────────
-- type: text, voice, stage, dm.
-- dm_pair_key: only set for type='dm'. Stable hash of the two participant ids
-- ("min:max" of stringified Snowflakes) — paired with the partial UNIQUE index
-- below it makes "open DM with X" idempotent: INSERT … ON CONFLICT DO NOTHING
-- + SELECT returns the pre-existing channel without race conditions.
CREATE TABLE IF NOT EXISTS channels (
    id              BIGINT PRIMARY KEY,
    hub_id          BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    type            TEXT NOT NULL DEFAULT 'text',   -- text, voice, stage, dm
    position        INT NOT NULL DEFAULT 0,
    icon_id         TEXT,
    icon_color      TEXT,
    icon_image_url  TEXT,
    dm_pair_key     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_channels_hub ON channels(hub_id);
-- Partial UNIQUE so non-DM channels (dm_pair_key IS NULL) are unconstrained.
CREATE UNIQUE INDEX IF NOT EXISTS idx_channels_dm_pair
    ON channels(hub_id, dm_pair_key) WHERE dm_pair_key IS NOT NULL;

-- ── DM participants ──────────────────────────────
-- Membership for type='dm' channels. Decoupled from member_groups because DMs
-- don't use the permission-bits model — participation alone grants R/W. Two
-- rows per DM (one per side); shape leaves room for group-DMs later (3+ rows).
CREATE TABLE IF NOT EXISTS dm_participants (
    channel_id  BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (channel_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_dm_participants_user ON dm_participants(user_id);

-- ── Groups ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS groups (
    id               BIGINT PRIMARY KEY,
    hub_id           BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    name             TEXT NOT NULL,
    color            TEXT,
    position         INT NOT NULL DEFAULT 0,
    is_default       BOOLEAN NOT NULL DEFAULT false,
    hub_permissions  INT NOT NULL DEFAULT 0,          -- bits 7-13
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_groups_hub ON groups(hub_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_groups_hub_default ON groups(hub_id) WHERE is_default = true;

-- ── Member <-> Group (many-to-many) ─────────────
CREATE TABLE IF NOT EXISTS member_groups (
    hub_id    BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    user_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    group_id  BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    PRIMARY KEY (hub_id, user_id, group_id)
);

-- ── Channel permissions per group ──────────────────
-- Per-channel permission bits (0-6). See models/permission.rs for the map.
CREATE TABLE IF NOT EXISTS channel_permissions (
    channel_id  BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    group_id    BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    allow_bits  INT NOT NULL DEFAULT 0,
    deny_bits   INT NOT NULL DEFAULT 0,
    PRIMARY KEY (channel_id, group_id)
);

-- ── Temporary users (side metadata) ────────────────────
-- The temp user's principal identity lives in `users` (user_type='temp').
-- This table only carries what's specific to the magic-link mechanism: the
-- secret token, the inviter, the active WS session, and a manual revoke
-- flag. The "is the link still good" gate is `expires_at` on users; this
-- table's `revoked_at` is the early-revoke override.
--
-- Pending vs walked-through:
--   * Row exists, active_session IS NULL → link issued, nobody walked yet
--     (shows up in pending-invites; users.id is NOT in hub_members yet)
--   * active_session IS NOT NULL → guest walked through; hub_members +
--     member_groups rows have been inserted at that point
CREATE TABLE IF NOT EXISTS temp_users (
    user_id         BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    hub_id          BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    token           TEXT NOT NULL UNIQUE,
    group_id        BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    created_by      BIGINT NOT NULL REFERENCES users(id),
    revoked_at      TIMESTAMPTZ,
    active_session  TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_temp_users_hub ON temp_users(hub_id);
CREATE INDEX IF NOT EXISTS idx_temp_users_token ON temp_users(token);

-- ── Permanent invitations ──────────────────────────
-- One row per invite link. `username` is allocated up front (admin picks
-- the login when creating the invite). `email` is informational only —
-- boxed has no SMTP, so the inviter copies the link manually.
-- Single-use: `used_at` flips from NULL to now() on acceptance, after
-- which the link returns 410 Gone.
--
-- The `username` column is the future users.username, and that table has
-- a global UNIQUE — but the invite isn't bound to a user yet. Multiple
-- pending invites for the same username are allowed; the race-loser hits
-- the users.username UNIQUE on accept and gets a clean error back.
CREATE TABLE IF NOT EXISTS invitations (
    id          BIGINT PRIMARY KEY,
    hub_id      BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    token       TEXT NOT NULL UNIQUE,
    username    TEXT NOT NULL,
    email       TEXT,
    group_id    BIGINT REFERENCES groups(id) ON DELETE SET NULL,
    created_by  BIGINT NOT NULL REFERENCES users(id),
    used_at     TIMESTAMPTZ,
    used_by     BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_invitations_hub
    ON invitations(hub_id) WHERE used_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_invitations_token
    ON invitations(token);

-- ── Refresh tokens ─────────────────────────────────
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          BIGINT PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    hub_id      BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    token_hash  TEXT NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON refresh_tokens(token_hash);

-- ── Row-Level Security ──────────────────────────────
-- Every hub-scoped query must execute after `SET LOCAL app.current_hub_id = '<bigint>'`.
-- RLS guarantees no cross-hub data leakage even if WHERE is forgotten.

ALTER TABLE groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY groups_hub_isolation ON groups
    USING (hub_id = current_setting('app.current_hub_id', true)::bigint);

ALTER TABLE channels ENABLE ROW LEVEL SECURITY;
CREATE POLICY channels_hub_isolation ON channels
    USING (hub_id = current_setting('app.current_hub_id', true)::bigint);

ALTER TABLE hub_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY hub_members_hub_isolation ON hub_members
    USING (hub_id = current_setting('app.current_hub_id', true)::bigint);

ALTER TABLE member_groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY member_groups_hub_isolation ON member_groups
    USING (hub_id = current_setting('app.current_hub_id', true)::bigint);

ALTER TABLE channel_permissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY channel_perms_hub_isolation ON channel_permissions
    USING (
        EXISTS (
            SELECT 1 FROM channels c
            WHERE c.id = channel_permissions.channel_id
              AND c.hub_id = current_setting('app.current_hub_id', true)::bigint
        )
    );

ALTER TABLE dm_participants ENABLE ROW LEVEL SECURITY;
CREATE POLICY dm_participants_hub_isolation ON dm_participants
    USING (
        EXISTS (
            SELECT 1 FROM channels c
            WHERE c.id = dm_participants.channel_id
              AND c.hub_id = current_setting('app.current_hub_id', true)::bigint
        )
    );

ALTER TABLE temp_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY temp_users_hub_isolation ON temp_users
    USING (hub_id = current_setting('app.current_hub_id', true)::bigint);

ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;
CREATE POLICY invitations_hub_isolation ON invitations
    USING (hub_id = current_setting('app.current_hub_id', true)::bigint);

-- Note: hubs and users tables are NOT under RLS.
--   hubs: root entity, looked up before hub_id is known.
--   users: global (shared across hubs).
