-- MateHub hub-service schema.
-- All IDs are 63-bit positive BIGINT Snowflakes generated by the application
-- (see matehub-common::snowflake). No sequences or uuid-ossp — generators live
-- in Rust so every service in the cluster agrees on the ID space.

-- ── Users ────────────────────────────────────────
-- account_id: link to the SaaS-side `general.accounts.id` for users that
-- came through SSO. NULL for on-prem users and temp_users — those live
-- entirely inside the hub. UNIQUE so one general account maps to exactly
-- one hub user (multiple NULLs allowed by Postgres).
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT PRIMARY KEY,
    username      TEXT NOT NULL UNIQUE,
    display_name  TEXT NOT NULL,
    avatar_url    TEXT,
    email         TEXT,
    password_hash TEXT,
    account_id    BIGINT UNIQUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email) WHERE email IS NOT NULL;

-- ── Hubs ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS hubs (
    id          BIGINT PRIMARY KEY,
    name        TEXT NOT NULL,
    slug        TEXT NOT NULL UNIQUE,
    plan        TEXT NOT NULL DEFAULT 'free',   -- free, pro, enterprise
    creator_id  BIGINT REFERENCES users(id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Hub members (many-to-many) ───────────────────
CREATE TABLE IF NOT EXISTS hub_members (
    hub_id        BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role          TEXT NOT NULL DEFAULT 'member',  -- admin, member, guest
    joined_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ,
    PRIMARY KEY (hub_id, user_id)
);

-- ── Channels ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS channels (
    id              BIGINT PRIMARY KEY,
    hub_id          BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    type            TEXT NOT NULL DEFAULT 'text',   -- text, voice, stage
    position        INT NOT NULL DEFAULT 0,
    icon_id         TEXT,
    icon_color      TEXT,
    icon_image_url  TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_channels_hub ON channels(hub_id);

-- ── Groups ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS groups (
    id               BIGINT PRIMARY KEY,
    hub_id           BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    name             TEXT NOT NULL,
    color            TEXT,
    position         INT NOT NULL DEFAULT 0,
    is_default       BOOLEAN NOT NULL DEFAULT false,
    hub_permissions  INT NOT NULL DEFAULT 0,          -- bits 7-13
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_groups_hub ON groups(hub_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_groups_hub_default ON groups(hub_id) WHERE is_default = true;

-- ── Member <-> Group (many-to-many) ─────────────
CREATE TABLE IF NOT EXISTS member_groups (
    hub_id    BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    user_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    group_id  BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    PRIMARY KEY (hub_id, user_id, group_id)
);

-- ── Channel permissions per group ──────────────────
-- Per-channel permission bits (0-6). See models/permission.rs for the map.
CREATE TABLE IF NOT EXISTS channel_permissions (
    channel_id  BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    group_id    BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    allow_bits  INT NOT NULL DEFAULT 0,
    deny_bits   INT NOT NULL DEFAULT 0,
    PRIMARY KEY (channel_id, group_id)
);

-- ── Temporary users ─────────────────────────────────
CREATE TABLE IF NOT EXISTS temp_users (
    id              BIGINT PRIMARY KEY,
    hub_id          BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    token           TEXT NOT NULL UNIQUE,           -- the magic-link secret
    nickname        TEXT NOT NULL,
    group_id        BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    created_by      BIGINT NOT NULL REFERENCES users(id),
    expires_at      TIMESTAMPTZ NOT NULL,
    revoked_at      TIMESTAMPTZ,
    active_session  TEXT,                            -- current WS session ID (null = nobody connected)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_temp_users_hub ON temp_users(hub_id);
CREATE INDEX IF NOT EXISTS idx_temp_users_token ON temp_users(token);

-- ── Refresh tokens ─────────────────────────────────
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          BIGINT PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    hub_id      BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    token_hash  TEXT NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON refresh_tokens(token_hash);

-- ── Row-Level Security ──────────────────────────────
-- Every hub-scoped query must execute after `SET LOCAL app.current_hub_id = '<bigint>'`.
-- RLS guarantees no cross-hub data leakage even if WHERE is forgotten.

ALTER TABLE groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY groups_hub_isolation ON groups
    USING (hub_id = current_setting('app.current_hub_id', true)::bigint);

ALTER TABLE channels ENABLE ROW LEVEL SECURITY;
CREATE POLICY channels_hub_isolation ON channels
    USING (hub_id = current_setting('app.current_hub_id', true)::bigint);

ALTER TABLE hub_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY hub_members_hub_isolation ON hub_members
    USING (hub_id = current_setting('app.current_hub_id', true)::bigint);

ALTER TABLE member_groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY member_groups_hub_isolation ON member_groups
    USING (hub_id = current_setting('app.current_hub_id', true)::bigint);

ALTER TABLE channel_permissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY channel_perms_hub_isolation ON channel_permissions
    USING (
        EXISTS (
            SELECT 1 FROM channels c
            WHERE c.id = channel_permissions.channel_id
              AND c.hub_id = current_setting('app.current_hub_id', true)::bigint
        )
    );

ALTER TABLE temp_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY temp_users_hub_isolation ON temp_users
    USING (hub_id = current_setting('app.current_hub_id', true)::bigint);

-- Note: hubs and users tables are NOT under RLS.
--   hubs: root entity, looked up before hub_id is known.
--   users: global (shared across hubs).
