use jsonwebtoken::{DecodingKey, EncodingKey, Header, Validation, decode, encode};
use serde::{Deserialize, Serialize};

/// JWT claims shared across services within a hub cluster (chat, video, hub).
/// `sub`, `hub_id`, `groups` are Snowflake i64 IDs generated by the hub service.
/// Secret is currently shared via `JWT_SECRET`; will become per-hub in SSO work (see #15).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Claims {
    /// User ID (permanent `users.id`) or temp user ID (`temp_users.id`).
    pub sub: i64,
    pub username: String,
    /// "permanent" or "temp"
    pub user_type: String,
    /// Hub ID this token is scoped to (hub's own `hubs.id`).
    pub hub_id: i64,
    /// Group IDs for permission checks.
    pub groups: Vec<i64>,
    pub iat: i64,
    pub exp: i64,
}

fn jwt_secret() -> Vec<u8> {
    std::env::var("JWT_SECRET")
        .unwrap_or_else(|_| "matehub-dev-secret-change-in-prod".into())
        .into_bytes()
}

pub fn create_token(claims: &Claims) -> Result<String, jsonwebtoken::errors::Error> {
    encode(
        &Header::default(),
        claims,
        &EncodingKey::from_secret(&jwt_secret()),
    )
}

pub fn verify_token(token: &str) -> Result<Claims, jsonwebtoken::errors::Error> {
    let data = decode::<Claims>(
        token,
        &DecodingKey::from_secret(&jwt_secret()),
        &Validation::default(),
    )?;
    Ok(data.claims)
}
